### ISSUE TITLE
Can i use it for Lubuntu?

### ISSUE THREAD

**Issue by ghprod** [baurigae/polar-night#3]
Hi noos here ..

can i use it for lubuntu?

Thanks

**Comment by baurigae** [comment]
The base GTK theme should work on Lubuntu, but last I looked LXDE uses Openbox WM and I have not included that, because I focus on what I use, Unity.
Basically you'd need a matching Openbox theme for window decorations (titlebars and such), and also the LXDE panel would have to be themed...

**Comment by ghprod** [comment]
Thanks a lot @baurigae .. i'll try it :dancer: 

:+1:

**Comment by baurigae** [comment]
Great I'd love to see it!
